### ISSUE TITLE
pointertap event doesn't work for ScrollBox items on mobile phone

### ISSUE THREAD

**Issue by gagrison** [pixijs/ui#100]
### Expected Behavior
pointertap event should work for items added inside ScrollBox
### Current Behavior
pointertap event doesn't work for ScrollBox items
### Steps to Reproduce
Create container with sprite inside, add  pointertap event on it. Make sure that there is enough height so scroll can be done. Add it to ScrollBox. Open application on mobile phone and try to click.
### Environment

- **version**: 0.9.0
- **Browser & Version**: Chrome  117.0.5938.140
- **OS & Version**: Android 13, Samsung SM-A536B

**Comment by CyberDex** [comment]
@gagrison 
Tried to reproduce this one, but no luck. Can you make some example on sandbox?
There is also a small thing to doublecheck:
in case if you are dragging a scrollbox even 1px, button event should not fire. 
This is a fix in case clicks on buttons is not intentional, but actually it is pressed to drag a scrollbox.

**Comment by gagrison** [comment]
Maybe this info will help. I made my own scroll box, and I had the same issue as reported here. I also made it that when you drag at least 1px all events are not propagated. But before that, I found out that **globaltouchmove** event is triggered on phones on touch with 0px drag (event.global.y).

**Comment by CyberDex** [comment]
Tested on both iPhone and Adnroid, both are firing pointertap event no problem. 
Can you reproduce your example in sandbox? Like https://codesandbox.io/

**Comment by gagrison** [comment]
If I find time I will. Since I made my own scrollbox this is not a priority sorry.

**Comment by gagrison** [comment]
@CyberDex here you go [link](https://codesandbox.io/s/frosty-rain-kgkdg3?file=/src/index.js)

**Comment by CyberDex** [comment]
@gagrison Thank you. Tried to reproduce on iphone and android, and all seems to work fine. Is it some specific device you are experiencing this on?

**Comment by gagrison** [comment]
I already wrote it. I also tried on Samsung S23+, same thing.

**Comment by thpoul** [comment]
Bump :)

**Comment by thpoul** [comment]
It doesn't work on the [official storybook](https://pixijs.io/ui/storybook/?path=/story/components-scrollbox-use-sprite--use-sprite) either. It's important not to use an emulator but a physical device.

**Comment by gagrison** [comment]
> @gagrison @thpoul Guys could you please check if v 0.10.4 fixes your problem?

It does
