### ISSUE TITLE
ScrollBox glitches elements on scroll if they are less then its height (macOS)

### ISSUE THREAD

**Issue by SergeiSomin** [pixijs/ui#113]
### Expected Behavior
Elements are either scrolled down or not scrollable at all in case elements height is less the ScrollBox height.

### Current Behavior
![bug](https://github.com/pixijs/ui/assets/35801681/4f70a6c1-f56d-4474-a7a5-3d36107c492e)

### Steps to Reproduce
1. Create ScrollBox.
2. Set its height.
3. Add elements and set their combined height to be less then ScrollBox height.
4. Scroll in one direction

Here is codesandbox with reproduction: 
https://codesandbox.io/s/funny-rgb-y4p46j?file=/src/index.js

### Environment
- **version**: pixijs: 7.3.1, @pixi/ui: 0.9.1
- **Browser & Version**: Version 118.0.5993.117 (Official Build) (x86_64)
- **OS & Version**: macOS 13.5 (22G74)
- **Running Example**: [_url_](https://codesandbox.io/s/funny-rgb-y4p46j?file=/src/index.js)

**Comment by CyberDex** [comment]
Thank you, @SergeiSomin. This is related to https://github.com/pixijs/ui/blob/b3b2fa6aa8c753665515bc4d530e99b1f851bd6a/src/ScrollBox.ts#L490
I think it would be enough just to add there a check for the size of the inner view size and skip scrolling if if is less than scroll box size. Do you  want to make a PR?

**Comment by SergeiSomin** [comment]
Yeah, got it, thanks, I will do PR
