### ISSUE TITLE
Is there support for virtual scrolling in ScrollBox

### ISSUE THREAD

**Issue by jickchen34** [pixijs/ui#123]
I am currently working with ScrollBox and need to handle large datasets efficiently. I would like to know whether ScrollBox supports virtual scrolling.

**Comment by sn4h** [comment]
Something lik position.x, position.y and position.set(x,y) would have been nice.

**Comment by CyberDex** [comment]
There is a `scrollTo` method (https://pixijs.io/ui/ScrollBox.html). The issue with performance is that all the items are rendered when scrolling. You will have to extend it to implement what you need.

**Comment by sn4h** [comment]
I managed to get the y position by listening to `scrollBox.items[0].parent.y` inside a ticker. I guess in my case is a rare one where I want to set the scroll start y position to a specific pixel.
