### ISSUE TITLE
Input() text is squished

### ISSUE THREAD

**Issue by reececomo** [pixijs/ui#128]
### Current Behavior

Text is squished into a fixed width area:

<img width="240" alt="Screenshot 2024-01-29 at 10 06 32 pm" src="https://github.com/pixijs/ui/assets/7390781/2de36925-e055-4b80-8c35-3ef34e7cdc56">
<img width="238" alt="Screenshot 2024-01-29 at 10 06 40 pm" src="https://github.com/pixijs/ui/assets/7390781/dfe66b34-e43d-4f90-a47f-219e258cc90b">
<img width="221" alt="Screenshot 2024-01-29 at 10 06 49 pm" src="https://github.com/pixijs/ui/assets/7390781/a2a53337-2a7b-4b71-8466-22a49f45a5d4">

Weirdly, placeholder text is unaffected (although it is awfully off-centre for 'center' aligned text):

<img width="215" alt="Screenshot 2024-01-29 at 10 11 56 pm" src="https://github.com/pixijs/ui/assets/7390781/fa3eba96-08a9-4687-baf0-71298a7fe2d2"><br/>

The amount of squash/stretching appears to be linked to the size of the `value` field.

<img width="101" alt="Screenshot 2024-01-29 at 10 52 53 pm" src="https://github.com/pixijs/ui/assets/7390781/7ff4ae2f-3b22-47f2-9d7c-98ea6de19b19"><br/>

<img width="237" alt="Screenshot 2024-01-29 at 10 51 39 pm" src="https://github.com/pixijs/ui/assets/7390781/1364d789-8fe0-4aa5-aee3-36a85fa9455c">
<img width="250" alt="Screenshot 2024-01-29 at 10 51 42 pm" src="https://github.com/pixijs/ui/assets/7390781/5618b766-2de7-4d30-be31-62baeacbc0f8">

And finally when no `value` is provided (same behaviour, width seems to be ~half the width of a single character):

<img width="247" alt="Screenshot 2024-01-29 at 10 53 48 pm" src="https://github.com/pixijs/ui/assets/7390781/1fca481f-9c27-4c20-8979-f40de03daadb">

### Expected Behavior

Text should appear normally, and not stretched out.

### Context

This is the entire code (honestly):

```ts
    this.$_nameField = new Input({
      placeholder: 'Enter text',
      bg,
      align: 'center',
      maxLength: 120,
      textStyle: {
        fontFamily: ['Arial', 'sans-serif'],
        fontWeight: 'bold',
        whiteSpace: 'normal',
      },
      value: 'example',
      padding: 8,
    });
    this.$_nameField.zIndex = 1_000;
    this.$rootView.addChild(this.$_nameField);
```

Is anyone seeing something similar?

**Comment by reececomo** [comment]
entire* code probably should include the `bg` `Graphics` object too:

```ts
    const borderColor = 0xcccccc;
    const backgroundColor = 0xeeeeee;
    const border = 3;
    const radius = 5;
    const width = 200;
    const height = 50;
    const bg = new Graphics()
      .beginFill(borderColor)
      .drawRoundedRect(0, 0, width, height, radius + border)
      .beginFill(backgroundColor)
      .drawRoundedRect(border, border, width - (border * 2), height - (border * 2), radius);
```

**Comment by CyberDex** [comment]
Hi, @reececomo 

Unfortunately I was not able to reproduce this issue. I have also checked all the usages of the pixi Text instance used here, and there are no places in code where size or scale is changing. You can check it here: https://github.com/pixijs/ui/blob/e77935ade04f994581bf4d13a4f36b55f6d180e9/src/Input.ts#L164

this.inputField is only used to get it's size and never set.

So in order to try to help I need either codepen example that reproduces this issue, or link to a repo (maybe if it is opensource)

**Comment by reececomo** [comment]
Yeah all good, I figure we (or a plugin) must be doing something somewhere that's causing this.

Thanks for looking, will close this ticket.
