### ISSUE TITLE
Slider: The event listening area for drag events should be the slider instead of the background

### ISSUE THREAD

**Issue by hotyes** [pixijs/ui#136]
**Please Describe The Problem To Be Solved**
The current event listener are adding on the bg instead of the slider, which is counterintuitive.

Sometimes we also want to design the background of the slider as a thin line, but the slider is larger. In the current behavior, it is not easy for the user to drag the slider.

![image](https://github.com/pixijs/ui/assets/34628616/b25970bb-efbf-4396-9988-6506ccdef5c3)

**(Optional): Suggest A Solution**

Add event listeners to "slider" instead of "bg", or to both.

**Comment by CyberDex** [comment]
Fixed in #137
