### ISSUE TITLE
Upgrade to work with pixi to 8.x

### ISSUE THREAD

**Issue by vcl00e** [pixijs/ui#146]
**Please Describe The Problem To Be Solved**
Hello, looks like this only works with pixi 7 and not with 8. 

**(Optional): Suggest A Solution**
I see that updating the import references to import from pixi.js instead of @pixi/xxxx   and removing the utils import solved alot of issues. The graphics code also seems depricated.

Not sure how we keep backward compatibility. Maybe we need to keep two branches? What do you think? I might be able to help if it's not too complex

**Comment by CyberDex** [comment]
There is a branch for v8. it is going to be merged and released soon. Yes version for v7 will live under the branch for an easier maintenance and will be released separately, same as pixiJS if configured.
