### ISSUE TITLE
Bug: `this.inputField` has its `style.align` set to `center` regardless of the `align` property

### ISSUE THREAD

**Issue by adam-savard** [pixijs/ui#154]
When using inputs, the `.style` property of `this.inputField` has its `.align` always set to `center`. While this is not a problem for single-line text, we're grafting multi-line support into things and this causes issues.

To confirm:

- Create a new input with `align: left`
- Check `input.inputField.style.align`

### Environment

- **version**: 2.0.1
- **Browser & Version**: Chrome 124
- **OS & Version**: Fedora 39

**Comment by adam-savard** [comment]
Hi! Not to be annoying, but I'm noticing that this is still an issue on 2.1.5!

**Comment by CyberDex** [comment]
This component's `input` field is a helper for reading keys and fake input behavior on mobile. 
We never show it, so applying styles will not do anything.
