### ISSUE TITLE
@pixi/ui 1.1.2 missing dist files

### ISSUE THREAD

**Issue by hotyes** [pixijs/ui#174]
### Expected Behavior
the installed packages should include dist and lib folder and js files

### Current Behavior
they are all missing, only package.json, LICENSE and README.md

### Environment

- **version**: 1.1.2
- **Browser & Version**: 
- **OS & Version**: OSX
- **Running Example**: 
- **PNPM**:  v9.4.0

**Comment by CyberDex** [comment]
Fixed in v1.1.3
