### ISSUE TITLE
Npm package for v1.1.2 is EMPTY (but 1.1.3 is not) — you may need to look into it

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [pixijs/ui#178]
### Expected Behavior
Downloading @pixi/ui@1.1.2 should download a working package

### Current Behavior

1.1.2 contains only package.json, readme, and a license file: https://www.npmjs.com/package/@pixi/ui/v/1.1.2?activeTab=code
(looks the same when npm install-ed on a machine)

but 1.1.3 is okay: https://www.npmjs.com/package/@pixi/ui/v/1.1.3?activeTab=code

### Possible Solution
???

### Steps to Reproduce
`npm install @pixi/ui@1.1.2`

### Also, note that there is [no release for v1.1.3](https://github.com/pixijs/ui/releases) on this repo.

**Comment by Zyie** [comment]
Hey, yeah we are aware that 1.1.2 accidently got released without any files, 1.1.3 was released to fix this
I've now added the 1.1.3 release to the repo
