### ISSUE TITLE
Mask input as default

### ISSUE THREAD

**Issue by CatchABus** [pixijs/ui#195]
**Please Describe The Problem To Be Solved**
Right now, input mask seems to be disabled by default. As a result, input text overlaps input as it grows.
This seems to be configurable with `addMask` property but this is not even documented.

**(Optional): Suggest A Solution**
Set `addMask` property default to `true`. This way, input will function just like a regular form input.

**Comment by CyberDex** [comment]
It was by default before but was removed as adding a mask to each input can affect the rendering performance as each mask adds one more draw call and breaks the batch. So now it is optional, and you can enable it only when you know what you are doing and ensure it will be OK with your rendering. I documented the setting, though; thank you!

**Comment by CatchABus** [comment]
> It was by default before but was removed as adding a mask to each input can affect the rendering performance as each mask adds one more draw call and breaks the batch. So now it is optional, and you can enable it only when you know what you are doing and ensure it will be OK with your rendering. I documented the setting, though; thank you!

Thank you so much for the detailed explanation!
