### ISSUE TITLE
Double text on input text mobile

### ISSUE THREAD

**Issue by patchanopjob** [pixijs/ui#196]
![Screenshot 2567-09-16 at 11 39 03](https://github.com/user-attachments/assets/3d9124c8-46dc-4833-b120-fe56e2653d46)

I press shift on keyboard double text 'AAAAA'

### Environment

- **version**: _e.g. 8.0.0_
- **Browser & Version**: _e.g. Chrome 67_
- **OS & Version**: _e.g. Ubuntu 18.04_
- **Running Example**: _url_

**Comment by CyberDex** [comment]
Hi, @patchanopjob. I'm sorry, I don't understand what the issue is. Could you please describe it in a bit more detail?

**Comment by CyberDex** [comment]
@patchanopjob Can you please test now [here](https://pixijs.io/ui/storybook/?path=/story/components-input-use-graphics--use-graphics)?
