### ISSUE TITLE
Step option for Slider is not supported in v1.1.3

### ISSUE THREAD

**Issue by hotyes** [pixijs/ui#199]
`step` option for Slider is not supported in v1.1.3

### Expected Behavior
`step` should be configurable and work as expected

### Current Behavior
Object literal may only specify known properties, and 'step' does not exist in type 'SliderOptions'.ts(2353)

### Environment

- **version**: 
    - "@pixi/ui": "1.1.3"
    - "pixi.js": "^7.4.2"

**Comment by CatchABus** [comment]
You should try latest 1.x.x version.
