### ISSUE TITLE
FancyButton capturing events outside of its expected range

### ISSUE THREAD

**Issue by ABViney** [pixijs/ui#54]
### Expected Behavior
non-click events should fire on interactive containers when a FancyButton is in the stage.

### Current Behavior
FancyButton object captures (at minimum) **all** pointerover, pointermove, and pointerout events, preventing other
listeners from receiving these.
Child elements of a FancyButton can be interacted with normally.
Adjacent elements can receive click events, but not hover events.

### Steps to Reproduce
https://github.com/ABViney/PixiUI-FancyButton-Bug/tree/main

This repo examples a simple demonstration.

**Comment by ABViney** [comment]
Did testing on Switcher and was unable to receive feedback from the same callbacks bound to other objects. The 'onHover' signal will fire if the cursor is intersecting it once it enters the DOM, whether that be tab swapping, or placing it on the edge of the screen.

Disabling the "addEvents" method in FancyButton stops occlusion of 'pointermove' events, but will also stop bounded listeners from firing on the innerView. Events still fire on child objects.

**Comment by CyberDex** [comment]
Hi, @ABViney, appreciate your help. The issue is related to setting of the `hitArea`, looks like there is a bug in pixi version 7.2.1. When you set the `hitArea`, it will take all size of the canvas. There is an issue work in progress([https://github.com/pixijs/pixijs/issues/9284](https://github.com/pixijs/pixijs/issues/9284)). We will update and close this one as soon as new version comes out.

**Comment by ABViney** [comment]
@CyberDex Good news! The initial issue I raised with `FancyButton` appears resolved with `Pixi.js@^7.2.3`. 

Bad news: The issues I found with `Switcher` do not appear to have changed. The bounded listeners will announce 'over' and 'out' sequentially only if the `onHover` signal fires, and I've only gotten it to fire when the Switcher's container is in the first intersection between the pointer and the stage.

Didn't want to jump to raising a new issue, since I had addressed it here already. Let me know (or beat me to it) if you'd rather that.

**Comment by CyberDex** [comment]
@ABViney we are working on next release, it should come in few days. `Switcher` has it's own issue that should be fixed in there. Meanwhile you can check if the issue is reproducible in the `react-patch` branch.

**Comment by ABViney** [comment]
@CyberDex Updated my repo adding the react-patch branch as a submodule. `Switcher` is behaving normally: `onHover` emits on `pointerover` of the `innerView` and pointer events register correctly on the `Switcher` object when `eventMode` is set appropriately.

As an aside, `tsc` has been complaining about the lambdas' parameter on lines `543` and `556` of `Scrollbox.ts` since `type never has no property 'renderable'`. Typing the parameters to `child: Container` made the errors go away--if that's reasonable to sneak into the next version.

Otherwise, all issues I've found appear resolved; I'll close this one out. Thank you for the hard work and transparency!
